name: Release at npm js

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 19.x
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build and install dependencies
        run: |
          npm install
          npm run build
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.METADATA_TRANSFORMER_NODEJS_AUTH_TOKEN }}
        run: npm publish --access public
